config_version: 2
settings:
  tabs.show:
    global: multiple
  url.default_page:
    global: https://google.com
  url.searchengines:
    global:
      DEFAULT: https://google.com/search?q={}
  url.start_pages:
    global: https://google.com
