theme:
  active: LightMagenta
  banner: LightCyan
  error_border: Red
  error_text: LightRed
  hint: Yellow
  hovered: LightYellow
  inactive: White
  playbar_background: Black
  playbar_progress: LightMagenta
  playbar_progress_text: Yellow
  playbar_text: White
  selected: Magenta
  text: "255, 255, 255"
  header: White

behavior:
  tick_rate_milliseconds: 150
  set_window_title: true
